Protein Databank Viewer
Visionome/frontend pull request #39
Opened 2022-03-04 03:39 UTC by APherwani

Updates:
- Add the molstar component
- Create custom component for gene info card
- Replace node-sass for sass because [node-sass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated)

2022-03-04 03:47 UTC, joeygiordano13 commented
Protein renders are loading in. We need to figure out eventually how to deal with genes without alphafold models.

2022-03-04 03:49 UTC, joeygiordano13 approved these changes
API call to prot database works. We can transition to something else long term, but this works for now.

2022-03-04 03:54 UTC, suneettipirneni requested changes

2022-03-04 03:54 UTC, suneettipirneni commented on src/components/GeneInfoCard.tsx
> +      let proteinId = proteinSelected.split('\n')[1];
```suggestion
      const [, proteinId] = proteinSelected.split('\n');
```

2022-03-04 03:54 UTC, suneettipirneni commented on src/components/GeneInfoCard.tsx
> +      console.log(response.data);
```suggestion
      const proteinSelected = await axios({
        method: 'get',
        url: `https://www.uniprot.org/uniprot/?query=${selectedItem.gene.toUpperCase()}+AND+reviewed:yes+AND+organism:9606&sort=score&columns=id&format=tab&limit=1`,
      }).then(r => {
        console.log(r.data);
        return r.data.toString()
      });
```

2022-03-05 03:07 UTC, APherwani commented on src/components/GeneInfoCard.tsx
> +      let proteinId = proteinSelected.split('\n')[1];
Fixed

2022-03-05 03:10 UTC, APherwani commented
> Protein renders are loading in. We need to figure out eventually how to deal with genes without alphafold models.

As discussed with Dr. Yooseph we can just inform the client that there is no such protein to render and call it a day.


> API call to prot database works. We can transition to something else long term, but this works for now.

I think this is fine. It's just a nice touch for our app it's not a primary feature. Downloading these and adding them to an S3 bucket will mean extra plumbing on the backend.

2022-03-05 19:42 UTC, APherwani commented
Forcing merge because I want to do some other things .

2022-03-05 19:42 UTC, merged